language: go

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  - DISPOSABLE_EMAILS_SOURCE=$HOME/gopath/src/github.com/0x19/disposable/services/burner/emails.txt

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - go get -v "github.com/smartystreets/goconvey"
  - go get -v "github.com/Sirupsen/logrus"
  - go get -v "github.com/asaskevich/govalidator"
  - go get -v "gopkg.in/tylerb/graceful.v1"
  - go get -v "github.com/gorilla/mux"
  - go get -v "github.com/koding/cache"
  - go get -v "google.golang.org/grpc"
  - go get -v "google.golang.org/grpc/credentials"
  - go get -v "github.com/satori/go.uuid"
  - go get -v "github.com/smartystreets/goconvey/convey"

script:
  - go test
