language: go

#
# I use SSH URLs in my submodules for convenience. However, Travis CI is unable to
# clone from those URLs even though the repositories are public. To fix this, I'm
# simply manipulating the .gitmodules file with sed so it points to the public
# URLs before initializing the submodules.
#
# Hope it saves you some frustration!
# https://gist.github.com/iedemam/9830045

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
 - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
 - git submodule init
 - git submodule update
 - git submodule foreach git checkout master
 - git submodule foreach git pull origin master

env:
  - DISPOSABLE_EMAILS_SOURCE=$HOME/gopath/src/github.com/0x19/disposable/services/burner/emails.txt
  - GRPC_KEY_FILE=$HOME/gopath/src/github.com/0x19/disposable/travis/certs/devserver.key
  - GRPC_CA_FILE=$HOME/gopath/src/github.com/0x19/disposable/travis/certs/devserver.crt
go:
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - go get -v "github.com/smartystreets/goconvey"
  - go get -v "github.com/Sirupsen/logrus"
  - go get -v "github.com/asaskevich/govalidator"
  - go get -v "gopkg.in/tylerb/graceful.v1"
  - go get -v "github.com/gorilla/mux"
  - go get -v "github.com/koding/cache"
  - go get -v "google.golang.org/grpc"
  - go get -v "google.golang.org/grpc/credentials"
  - go get -v "github.com/satori/go.uuid"
  - go get -v "github.com/smartystreets/goconvey/convey"

script:
  - go test -run=TestTravis
