language: go

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    
go:
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - go get -v "github.com/smartystreets/goconvey"
  - go get -v "github.com/Sirupsen/logrus"

script:
  - go test
